#!/usr/bin/env cwl-runner

# (Re)generated by BlueBee Platform

$namespaces:
  bb: http://bluebee.com/cwl/
  ilmn-tes: http://platform.illumina.com/rdf/iap/
cwlVersion: cwl:v1.0
class: CommandLineTool
bb:toolVersion: '2'
requirements:
- class: InlineJavascriptRequirement
- class: InitialWorkDirRequirement
  listing:
  - "${\n    var output_array = [];\n     for(var i=1; i<= inputs.FASTQ_files.length;\
    \ i++){ \n        output_array.push(inputs.FASTQ_files[i-1]);\n    } \n     if(inputs.design_file){\
    \ \n        output_array.push(inputs.design_file);\n    }  \n     if(inputs.reference_file){\
    \ \n        output_array.push( inputs.reference_file); \n     }  \n    return\
    \ output_array\n}\n"
label: goal_dna_monolith_tool
inputs:
  FASTQ_files:
    type:
      type: array
      items: File
    inputBinding:
      position: 1
      prefix: --fastq_files
  reference_file:
    type: File
    inputBinding:
      position: 2
      prefix: --ref
  viral_reference:
    type: File
    secondaryFiles:
    - .bwt
    - .sa
    - .amb
    - .ann
    - .pac
    inputBinding:
      position: 3
      prefix: --virus_ref
  design_file:
    type:
    - File
    - 'null'
    doc: |-
      Design file for tumor-normal analyses. By default the tool wrapper will create a tumor-only table as referenced here:

      https://github.com/bcantarel/school
    inputBinding:
      position: 8
      prefix: --design
  markduplicates_method:
    type: string
    inputBinding:
      position: 6
      prefix: --markdups
  tool_version:
    type: string
    inputBinding:
      position: 7
      prefix: --version
outputs:
  outputs:
    type:
    - Directory
    - 'null'
    outputBinding:
      glob:
      - $(runtime.outdir)
  html_reports:
    type:
    - type: array
      items: File
    - 'null'
    outputBinding:
      glob:
      - '*html'
arguments:
- position: 8
  prefix: --output_directory
  valueFrom: $(runtime.outdir)/analysis
- position: 5
  prefix: --bed
  valueFrom: $(runtime.outdir)/new_goal_reference/targetpanel.bed
- position: 6
  prefix: --pon
  valueFrom: $(runtime.outdir)/new_goal_reference/mutect2.pon.vcf.gz
baseCommand:
- python3
- /usr/local/bin/tool_wrapper_nf.py
